version: "3.8"
services:
  
  # Redis
  redis:
    image: redis:latest
    restart: always
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_volume:/data
# Defining Volumes
volumes:
  
  redis_volume:
    driver: local