export const initialDashboardData = [
  { tabName: 'dashboard' },
  { tabName: 'master' },
  { tabName: 'addaccess' },
  { tabName: 'admissionAction ' },
  { tabName: 'admissionprocess' },
  { tabName: 'extradocuments' },
  { tabName: 'payments' },
  { tabName: 'studentManagement' },
  { tabName: 'errata' },
  { tabName: 'extradocuments' },
  // { tabName: 'meritlist' },
  // { tabName: 'viewMeritlist' },
  // { tabName: 'verificationtab ' },
  { tabName: 'collegeApplications ' },
  { tabName: 'collegeReport ' },
  { tabName: 'universityApplications ' },
  { tabName: 'sortByUniversity ' },
  { tabName: 'downloads ' },
  // { tabName: 'managementQuota ' },
  { tabName: 'activitytracking ' },
  { tabName: 'ticket' },
  { tabName: 'phdRegistrations' },
  { tabName: 'sfcConvocation ' }

];