import Joi from 'joi';


const personalDataSchema = Joi.object({
    id: Joi.number().integer().required(),
    firstName: Joi.string().trim().allow('', null).optional(),
    lastName: Joi.string().trim().allow('', null).optional(),
    nameAsOnMarksheet: Joi.string().trim().allow('', null).optional(),
    email: Joi.string().email().required(),
    mobileno: Joi.string().trim().allow('', null).optional(),
    dob: Joi.date().iso().required(),
    gender: Joi.string().trim().allow('', null).optional(),
    bloodGroup: Joi.string().trim().allow('', null).optional(),
    nameAsPerAadharCard: Joi.string().trim().allow('', null).optional(),
    aadharCardno: Joi.string().trim().allow('', null).optional(),
    city: Joi.string().trim().allow('', null).optional(),
    state: Joi.string().trim().allow('', null).optional(),
    address: Joi.string().trim().allow('', null).optional(),
    religion: Joi.string().trim().allow('', null).optional(),
    minority: Joi.string().trim().allow('', null).optional(),
    pincode: Joi.string().trim().allow('', null).optional(),
    motherName: Joi.string().trim().allow('', null).optional(),
    fatherName: Joi.string().trim().allow('', null).optional(),
    parentsMobileno: Joi.string().trim().allow('', null).optional(),
    admissionType: Joi.string().trim().allow('', null).optional(),
    admissionCategory: Joi.string().trim().allow('', null).optional(),
    role: Joi.string().trim().allow('', null).optional(),
    keycloakId: Joi.string().trim().allow('', null).optional(),
    status: Joi.allow(null).optional(),
    registrationNo: Joi.number().integer().optional(),
    imagesName: Joi.allow(null).optional(),
    learningDisability: Joi.string().trim().allow('', null).optional(),
    category: Joi.string().trim().allow('', null).optional(),
    academicYear: Joi.number().integer().optional(),
    createdAt: Joi.date().iso().optional(),
    updatedAt: Joi.date().iso().optional(),
    registerYear: Joi.string().trim().allow('', null).optional(),
    placeOfBirth: Joi.string().trim().allow('', null).optional(),
    voterName: Joi.string().trim().allow('', null).optional(),
    motherTongue: Joi.string().trim().allow('', null).optional(),
    educationGap: Joi.number().allow('', null).optional(),
    citizenShip: Joi.string().trim().allow('', null).optional(),
    abcId: Joi.number().allow('', null).optional(),
    middleName:Joi.string().allow('', null).optional(),
    corCity:Joi.string().allow('', null).optional(),
    corState:Joi.string().allow('', null).optional(),
    corAddress:Joi.string().allow('', null).optional(),
    corPincode:Joi.string().allow('', null).optional(),
    corLocationArea:Joi.string().allow('', null).optional(),
    corDistrict:Joi.string().allow('', null).optional(),
    corTaluka:Joi.string().allow('', null).optional(),
    guardianMobileno:Joi.string().allow('', null).optional(),
    guardianAnnualIncome:Joi.string().allow('', null).optional(),
    guardianOccupation:Joi.string().allow('', null).optional(),
    guardianName:Joi.string().allow('', null).optional(),
    relationWithGuardian:Joi.string().allow('', null).optional(),
    employeeStatus:Joi.string().allow('', null).optional(),
    preAddress:Joi.string().allow('', null).optional(),
    prePincode:Joi.string().allow('', null).optional(),
    preCity:Joi.string().allow('', null).optional(),
    preState:Joi.string().allow('', null).optional(),
    preLocationArea:Joi.string().allow('', null).optional(),
    preDistrict:Joi.string().allow('', null).optional(),
    preTaluka:Joi.string().allow('', null).optional(),
    speciallyAbled:Joi.string().allow('', null).optional(),
    domicileState:Joi.string().allow('', null).optional(),
    maritalStatus:Joi.string().allow('', null).optional(),
    isAddressSame:Joi.string().allow('', null).optional(),
    nameInRegional:Joi.string().allow('', null).optional()
  });

  const documentSchema = Joi.object({
    id: Joi.number().integer().required(),
    documentType: Joi.string().trim().required(),
    filePath: Joi.string().trim().required(),
    extension: Joi.string().trim().required(),
    fileName: Joi.string().trim().required(),
    errata: Joi.allow(null).optional(),
    updated_step: Joi.allow(null).optional(),
    verify: Joi.string().trim().required(),
    admissionType:  Joi.string().trim().required()
  });

  const educationDataSchema = Joi.object({
    id: Joi.number().integer().required(),
    userId: Joi.number().integer().required(),
    sscObtainedMarks: Joi.number().integer().allow(null).required(),
    sscOutOf: Joi.number().integer().allow(null).required(),
    sscPercentage: Joi.string().trim().required().allow(null),
    sscGrade: Joi.allow(null).optional(),
    hscBoard: Joi.allow(null).optional(),
    hscCollegeName: Joi.string().trim().allow('', null).optional(),
    hscPassingState: Joi.string().trim().allow('', null).optional(),
    hscPassingYear: Joi.number().integer().allow(null).optional(),
    hscPassingMonth: Joi.string().trim().allow('', null).optional(),
    hscSeatNo: Joi.string().trim().allow('', null).optional(),
    hscMarksObtained: Joi.number().integer().allow(null).optional(),
    hscOutOf: Joi.number().integer().allow(null).optional(),
    hscStream: Joi.string().trim().allow('', null).optional(),
    hscGrade: Joi.allow(null).optional(),
    hscNoOfAttempt: Joi.number().integer().allow(null).optional(),
    hscPercentage: Joi.string().trim().allow('', null).optional(),
    achievements: Joi.allow(null).optional(),
    biologyPercentage: Joi.allow(null).optional(),
    mathPercentage: Joi.allow(null).optional(),
    ugCollegename: Joi.allow(null).optional(),
    ugCourseName: Joi.allow(null).optional(),
    ugPassingMonth: Joi.allow(null).optional(),
    ugPassingYear: Joi.allow(null).optional(),
    ugSeatNo: Joi.allow(null).optional(),
    ugNoOfAttempt: Joi.allow(null).optional(),
    ugEntranceMarks: Joi.allow(null).optional(),
    EntranceExam: Joi.allow(null).optional(),
    EntranceYear: Joi.allow(null).optional(),
    resultStatus: Joi.string().trim().allow('', null).optional(),
    ugMarksObtained: Joi.allow(null).optional(),
    ugOutof: Joi.allow(null).optional(),
    ugPercentage: Joi.allow(null).optional(),
    ugGrade: Joi.allow(null).optional(),
    ugselectChoice: Joi.allow(null).optional(),
    hscselectChoice: Joi.string().trim().allow('', null).optional(),
    sscselectChoice: Joi.string().trim().allow('', null).optional(),
    ugQualificationName: Joi.allow(null).optional(),
    admissionYear: Joi.number().integer().optional(),
    admissionType: Joi.string().trim().allow('', null).optional(),
    inHouse: Joi.string().trim().allow('', null).optional(),
    createdAt: Joi.date().iso().allow(null).optional(),
    updatedAt: Joi.date().iso().allow(null).optional(),
    boardtype: Joi.string().trim().allow('', null).optional(),
    sscPassingState: Joi.string().trim().allow('', null).optional(),
    sscBoardName: Joi.string().trim().allow('', null).optional(),
    sscCollegeName: Joi.string().trim().allow('', null).optional(),
    sscPassingMonth: Joi.string().trim().allow('', null).optional(),
    sscPassingYear: Joi.number().allow('', null).optional(),
    hscBoardName: Joi.string().trim().allow('', null).optional(),
    sscSeatNo: Joi.string().trim().allow('', null).optional()

  });



  export const downloadAdmissionFormSchema = Joi.object({
    userId: Joi.number().required(),
    personalData: personalDataSchema.required(),
    eduData: educationDataSchema.required(),
    documentData: Joi.array().items(documentSchema).required()
  });